### ISSUE TITLE
about dependencies

### ISSUE THREAD

**Issue by zxy981123** [neo-technology/front-end#16]
When I run this project, there is no CharStream, token. And then I add a org.opencypher:cypher-javacc-parser-9.0.jar to the project. And still, there is some symbol that cannot be found. I do not know if I should add an extra dependency.
![image](https://user-images.githubusercontent.com/59109169/174136518-eb418fd8-fc48-4940-9fce-3a607c5de9ec.png)

**Comment by mnd999** [comment]
Did you try building with maven? Most likely the generated code for the javacc parser is out of date. A maven build will regenerate it.

**Comment by zxy981123** [comment]
> Did you try building with maven? Most likely the generated code for the javacc parser is out of date. A maven build will regenerate it.
Thank you for your help. I succeed to run it. I use IntelliJ and its Maven is not useful, I install the one from Apache, and then rerunning mvn clean install in the terminal and then reload the directory. It is workful.
