### ISSUE TITLE
Confusing licensing in cypher.jj

### ISSUE THREAD

**Issue by tapdiego-amzn** [neo-technology/front-end#21]
The following file seems to be identified as licensed under both Apache-2.0 and GPL-3.0: https://github.com/opencypher/front-end/blob/f6eb443b5fae17aa9f672a2115a89b502a7fdd29/javacc-parser/src/main/java/org/opencypher/v9_0/parser/javacc/cypher.jj

It would be interesting to know whether both of those licenses apply to the file or it is only Apache-2.0 just like the rest of the project.

**Comment by mnd999** [comment]
This appears to be an error caused by the `.jj` file confusing an automated job that writes to opencypher respository. The license should be consistent across the project - we'll get it fixed.

**Comment by Lojjs** [comment]
@tapdiego-amzn Thanks for your patience, this has now been addressed in https://github.com/opencypher/front-end/commit/07f58c5a291fb868c8a5506e2dcf1e3379f653e9. The correct license should be Apache-2.0

**Comment by tapdiego-amzn** [comment]
Thank you!
